name:                constretto
version:             0.1.0.0
github:              "mariatsji/constretto"
license:             BSD3
author:              "Sjur Millidahl"
maintainer:          "sjur.millidahl@gmail.com"
copyright:           "BSD-3-Clause"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mariatsji/constretto#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - containers
  - text

tests:
  constretto-test:
    main:                Specs.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - constretto
    - hspec
    - containers
    - text
    - directory
    - attoparsec
